#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseDLCButton

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass BaseDLCButton.BaseDLCButton_C
// 0x0000 (0x0B98 - 0x0B98)
class UBaseDLCButton_C final : public UButtonBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BaseDLCButton_C">();
	}
	static class UBaseDLCButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBaseDLCButton_C>();
	}
};
static_assert(alignof(UBaseDLCButton_C) == 0x000008, "Wrong alignment on UBaseDLCButton_C");
static_assert(sizeof(UBaseDLCButton_C) == 0x000B98, "Wrong size on UBaseDLCButton_C");

}

