#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseDLCWidget_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass BaseDLCWidget_BP.BaseDLCWidget_BP_C
// 0x0000 (0x0450 - 0x0450)
class UBaseDLCWidget_BP_C final : public UMainMenuDLCWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BaseDLCWidget_BP_C">();
	}
	static class UBaseDLCWidget_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBaseDLCWidget_BP_C>();
	}
};
static_assert(alignof(UBaseDLCWidget_BP_C) == 0x000008, "Wrong alignment on UBaseDLCWidget_BP_C");
static_assert(sizeof(UBaseDLCWidget_BP_C) == 0x000450, "Wrong size on UBaseDLCWidget_BP_C");

}

