#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StarField

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass BP_StarField.BP_StarField_C
// 0x0000 (0x02C8 - 0x02C8)
class ABP_StarField_C final : public AStaticMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StarField_C">();
	}
	static class ABP_StarField_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StarField_C>();
	}
};
static_assert(alignof(ABP_StarField_C) == 0x000008, "Wrong alignment on ABP_StarField_C");
static_assert(sizeof(ABP_StarField_C) == 0x0002C8, "Wrong size on ABP_StarField_C");

}

