#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Button1_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass Button1_BP.Button1_BP_C
// 0x0000 (0x0B98 - 0x0B98)
class UButton1_BP_C final : public UButtonBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button1_BP_C">();
	}
	static class UButton1_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButton1_BP_C>();
	}
};
static_assert(alignof(UButton1_BP_C) == 0x000008, "Wrong alignment on UButton1_BP_C");
static_assert(sizeof(UButton1_BP_C) == 0x000B98, "Wrong size on UButton1_BP_C");

}

