#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CE_Concuss_PostProcess

#include "Basic.hpp"

#include "CE_Concuss_PostProcess_classes.hpp"
#include "CE_Concuss_PostProcess_parameters.hpp"


namespace CG
{

// Function CE_Concuss_PostProcess.CE_Concuss_PostProcess_C.ExecuteUbergraph_CE_Concuss_PostProcess
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCE_Concuss_PostProcess_C::ExecuteUbergraph_CE_Concuss_PostProcess(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CE_Concuss_PostProcess_C", "ExecuteUbergraph_CE_Concuss_PostProcess");

	Params::CE_Concuss_PostProcess_C_ExecuteUbergraph_CE_Concuss_PostProcess Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CE_Concuss_PostProcess.CE_Concuss_PostProcess_C.ReceiveApplyEffect
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Ratio                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bRestoredFromSave                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCE_Concuss_PostProcess_C::ReceiveApplyEffect(class AActor* Target, float Param_Ratio, bool bRestoredFromSave)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CE_Concuss_PostProcess_C", "ReceiveApplyEffect");

	Params::CE_Concuss_PostProcess_C_ReceiveApplyEffect Parms{};

	Parms.Target = Target;
	Parms.Param_Ratio = Param_Ratio;
	Parms.bRestoredFromSave = bRestoredFromSave;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CE_Concuss_PostProcess.CE_Concuss_PostProcess_C.ReceiveClearEffect
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCE_Concuss_PostProcess_C::ReceiveClearEffect(class AActor* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CE_Concuss_PostProcess_C", "ReceiveClearEffect");

	Params::CE_Concuss_PostProcess_C_ReceiveClearEffect Parms{};

	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}

}

