#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IndianaGameModeFrontEnd

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass IndianaGameModeFrontEnd.IndianaGameModeFrontEnd_C
// 0x0008 (0x03E0 - 0x03D8)
class AIndianaGameModeFrontEnd_C final : public AIndianaGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IndianaGameModeFrontEnd_C">();
	}
	static class AIndianaGameModeFrontEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AIndianaGameModeFrontEnd_C>();
	}
};
static_assert(alignof(AIndianaGameModeFrontEnd_C) == 0x000008, "Wrong alignment on AIndianaGameModeFrontEnd_C");
static_assert(sizeof(AIndianaGameModeFrontEnd_C) == 0x0003E0, "Wrong size on AIndianaGameModeFrontEnd_C");
static_assert(offsetof(AIndianaGameModeFrontEnd_C, DefaultSceneRoot) == 0x0003D8, "Member 'AIndianaGameModeFrontEnd_C::DefaultSceneRoot' has a wrong offset!");

}

