#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LegalWidget_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass LegalWidget_BP.LegalWidget_BP_C
// 0x0018 (0x0400 - 0x03E8)
class ULegalWidget_BP_C final : public ULegalWidget
{
public:
	class UImage*                                 BackingBot;                                        // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackingTop;                                        // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Frame;                                             // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LegalWidget_BP_C">();
	}
	static class ULegalWidget_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULegalWidget_BP_C>();
	}
};
static_assert(alignof(ULegalWidget_BP_C) == 0x000008, "Wrong alignment on ULegalWidget_BP_C");
static_assert(sizeof(ULegalWidget_BP_C) == 0x000400, "Wrong size on ULegalWidget_BP_C");
static_assert(offsetof(ULegalWidget_BP_C, BackingBot) == 0x0003E8, "Member 'ULegalWidget_BP_C::BackingBot' has a wrong offset!");
static_assert(offsetof(ULegalWidget_BP_C, BackingTop) == 0x0003F0, "Member 'ULegalWidget_BP_C::BackingTop' has a wrong offset!");
static_assert(offsetof(ULegalWidget_BP_C, Frame) == 0x0003F8, "Member 'ULegalWidget_BP_C::Frame' has a wrong offset!");

}

