#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LevelSelectOptions_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass LevelSelectOptions_BP.LevelSelectOptions_BP_C
// 0x0008 (0x0340 - 0x0338)
class ULevelSelectOptions_BP_C final : public ULevelOptionsWidget
{
public:
	class UBorder*                                OptionsContainer;                                  // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LevelSelectOptions_BP_C">();
	}
	static class ULevelSelectOptions_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULevelSelectOptions_BP_C>();
	}
};
static_assert(alignof(ULevelSelectOptions_BP_C) == 0x000008, "Wrong alignment on ULevelSelectOptions_BP_C");
static_assert(sizeof(ULevelSelectOptions_BP_C) == 0x000340, "Wrong size on ULevelSelectOptions_BP_C");
static_assert(offsetof(ULevelSelectOptions_BP_C, OptionsContainer) == 0x000338, "Member 'ULevelSelectOptions_BP_C::OptionsContainer' has a wrong offset!");

}

