#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainOptions_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"
#include "Engine_structs.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass MainOptions_BP.MainOptions_BP_C
// 0x0050 (0x0430 - 0x03E0)
class UMainOptions_BP_C final : public UMainOptionsWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlockBase*                         ChangeProfileText;                                 // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         ContinueText;                                      // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         CreditsText;                                       // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         DeliverablesText;                                  // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         ExtrasText;                                        // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         LoadSaveText;                                      // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         NewGameText;                                       // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         QuitText;                                          // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlockBase*                         SettingsText;                                      // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MainOptions_BP(int32 EntryPoint);
	void BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);
	void BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainOptions_BP_C">();
	}
	static class UMainOptions_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainOptions_BP_C>();
	}
};
static_assert(alignof(UMainOptions_BP_C) == 0x000008, "Wrong alignment on UMainOptions_BP_C");
static_assert(sizeof(UMainOptions_BP_C) == 0x000430, "Wrong size on UMainOptions_BP_C");
static_assert(offsetof(UMainOptions_BP_C, UberGraphFrame) == 0x0003E0, "Member 'UMainOptions_BP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, ChangeProfileText) == 0x0003E8, "Member 'UMainOptions_BP_C::ChangeProfileText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, ContinueText) == 0x0003F0, "Member 'UMainOptions_BP_C::ContinueText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, CreditsText) == 0x0003F8, "Member 'UMainOptions_BP_C::CreditsText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, DeliverablesText) == 0x000400, "Member 'UMainOptions_BP_C::DeliverablesText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, ExtrasText) == 0x000408, "Member 'UMainOptions_BP_C::ExtrasText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, LoadSaveText) == 0x000410, "Member 'UMainOptions_BP_C::LoadSaveText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, NewGameText) == 0x000418, "Member 'UMainOptions_BP_C::NewGameText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, QuitText) == 0x000420, "Member 'UMainOptions_BP_C::QuitText' has a wrong offset!");
static_assert(offsetof(UMainOptions_BP_C, SettingsText) == 0x000428, "Member 'UMainOptions_BP_C::SettingsText' has a wrong offset!");

}

