#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainOptions_BP

#include "Basic.hpp"

#include "Indiana_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace CG::Params
{

// Function MainOptions_BP.MainOptions_BP_C.ExecuteUbergraph_MainOptions_BP
// 0x0AB8 (0x0AB8 - 0x0000)
struct MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1761[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event;                  // 0x0008(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_35;               // 0x0038(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_34;               // 0x0068(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_33;               // 0x0098(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_32;               // 0x00C8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_31;               // 0x00F8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_30;               // 0x0128(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_29;               // 0x0158(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_28;               // 0x0188(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_27;               // 0x01B8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_26;               // 0x01E8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_25;               // 0x0218(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_24;               // 0x0248(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_23;               // 0x0278(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_22;               // 0x02A8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue;               // 0x02D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_1;             // 0x02E8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x02F8(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0320(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_2;             // 0x0348(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_3;             // 0x0358(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_2;                    // 0x0368(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_3;                    // 0x0390(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_4;             // 0x03B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_5;             // 0x03C8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_4;                    // 0x03D8(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_5;                    // 0x0400(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_6;             // 0x0428(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_6;                    // 0x0438(0x0028)()
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_21;               // 0x0460(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_20;               // 0x0490(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_19;               // 0x04C0(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_18;               // 0x04F0(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_17;               // 0x0520(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_16;               // 0x0550(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_15;               // 0x0580(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_14;               // 0x05B0(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_13;               // 0x05E0(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_12;               // 0x0610(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_11;               // 0x0640(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_10;               // 0x0670(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_9;                // 0x06A0(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_8;                // 0x06D0(0x0030)(ConstParm, ContainsInstancedReference)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_7;             // 0x0700(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_8;             // 0x0710(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_7;                    // 0x0720(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_8;                    // 0x0748(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_9;             // 0x0770(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_10;            // 0x0780(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_9;                    // 0x0790(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_10;                   // 0x07B8(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_11;            // 0x07E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_12;            // 0x07F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_11;                   // 0x0800(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_12;                   // 0x0828(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_13;            // 0x0850(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_7;                // 0x0860(0x0030)(ConstParm, ContainsInstancedReference)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_13;                   // 0x0890(0x0028)()
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_6;                // 0x08B8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_5;                // 0x08E8(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_4;                // 0x0918(0x0030)(ConstParm, ContainsInstancedReference)
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_14;            // 0x0948(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_14;                   // 0x0958(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_15;            // 0x0980(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_15;                   // 0x0990(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_16;            // 0x09B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_16;                   // 0x09C8(0x0028)()
	struct FLinearColor                           CallFunc_GetColorByType_ReturnValue_17;            // 0x09F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_17;                   // 0x0A00(0x0028)()
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_3;                // 0x0A28(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_2;                // 0x0A58(0x0030)(ConstParm, ContainsInstancedReference)
	struct FComponentEvent                        K2Node_ComponentBoundEvent_Event_1;                // 0x0A88(0x0030)(ConstParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP) == 0x000008, "Wrong alignment on MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP");
static_assert(sizeof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP) == 0x000AB8, "Wrong size on MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, EntryPoint) == 0x000000, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event) == 0x000008, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_35) == 0x000038, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_35' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_34) == 0x000068, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_34' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_33) == 0x000098, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_33' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_32) == 0x0000C8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_32' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_31) == 0x0000F8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_31' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_30) == 0x000128, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_30' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_29) == 0x000158, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_29' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_28) == 0x000188, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_28' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_27) == 0x0001B8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_27' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_26) == 0x0001E8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_26' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_25) == 0x000218, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_25' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_24) == 0x000248, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_24' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_23) == 0x000278, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_23' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_22) == 0x0002A8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_22' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue) == 0x0002D8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_1) == 0x0002E8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor) == 0x0002F8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_1) == 0x000320, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_2) == 0x000348, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_3) == 0x000358, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_2) == 0x000368, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_2' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_3) == 0x000390, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_3' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_4) == 0x0003B8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_5) == 0x0003C8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_4) == 0x0003D8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_4' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_5) == 0x000400, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_5' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_6) == 0x000428, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_6) == 0x000438, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_6' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_21) == 0x000460, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_21' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_20) == 0x000490, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_20' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_19) == 0x0004C0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_19' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_18) == 0x0004F0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_18' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_17) == 0x000520, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_17' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_16) == 0x000550, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_16' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_15) == 0x000580, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_15' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_14) == 0x0005B0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_14' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_13) == 0x0005E0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_13' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_12) == 0x000610, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_12' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_11) == 0x000640, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_11' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_10) == 0x000670, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_10' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_9) == 0x0006A0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_9' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_8) == 0x0006D0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_8' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_7) == 0x000700, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_8) == 0x000710, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_7) == 0x000720, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_7' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_8) == 0x000748, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_8' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_9) == 0x000770, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_10) == 0x000780, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_9) == 0x000790, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_9' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_10) == 0x0007B8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_10' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_11) == 0x0007E0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_12) == 0x0007F0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_11) == 0x000800, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_11' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_12) == 0x000828, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_12' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_13) == 0x000850, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_7) == 0x000860, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_7' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_13) == 0x000890, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_13' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_6) == 0x0008B8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_6' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_5) == 0x0008E8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_5' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_4) == 0x000918, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_4' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_14) == 0x000948, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_14) == 0x000958, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_14' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_15) == 0x000980, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_15) == 0x000990, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_15' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_16) == 0x0009B8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_16) == 0x0009C8, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_16' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, CallFunc_GetColorByType_ReturnValue_17) == 0x0009F0, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::CallFunc_GetColorByType_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_MakeStruct_SlateColor_17) == 0x000A00, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_MakeStruct_SlateColor_17' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_3) == 0x000A28, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_3' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_2) == 0x000A58, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_2' has a wrong offset!");
static_assert(offsetof(MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP, K2Node_ComponentBoundEvent_Event_1) == 0x000A88, "Member 'MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP::K2Node_ComponentBoundEvent_Event_1' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature final
{
public:
	struct FComponentEvent                        Event;                                             // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature) == 0x000008, "Wrong alignment on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature");
static_assert(sizeof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature) == 0x000030, "Wrong size on MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature");
static_assert(offsetof(MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature, Event) == 0x000000, "Member 'MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature::Event' has a wrong offset!");

}

