#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Main

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Indiana_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace CG::Params
{

// Function Main.Main_C.ExecuteUbergraph_Main
// 0x0170 (0x0170 - 0x0000)
struct Main_C_ExecuteUbergraph_Main final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEvent2D_ReturnValue;                  // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29EC[0x4];                                     // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBranches                                CallFunc_GetIndianaUI_Branches;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29ED[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AIndianaUI*                             CallFunc_GetIndianaUI_ReturnValue;                 // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBranches                                CallFunc_ConstructUserWidget_Branches;             // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29EE[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UIndianaInterfaceUserWidget*            CallFunc_ConstructUserWidget_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UIndianaGameInstance*                   K2Node_DynamicCast_AsIndiana_Game_Instance;        // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29EF[0x1];                                     // 0x0053(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_Multiply_RotatorFloat_ReturnValue;        // 0x0054(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_AddActorWorldRotation_SweepHitResult;  // 0x0060(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddActorWorldRotation_SweepHitResult_1; // 0x00E8(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Main_C_ExecuteUbergraph_Main) == 0x000008, "Wrong alignment on Main_C_ExecuteUbergraph_Main");
static_assert(sizeof(Main_C_ExecuteUbergraph_Main) == 0x000170, "Wrong size on Main_C_ExecuteUbergraph_Main");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, EntryPoint) == 0x000000, "Member 'Main_C_ExecuteUbergraph_Main::EntryPoint' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_PostEvent2D_ReturnValue) == 0x000004, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_PostEvent2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, K2Node_Event_DeltaSeconds) == 0x000008, "Member 'Main_C_ExecuteUbergraph_Main::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_GetPlayerController_ReturnValue) == 0x000010, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_GetPlayerController_ReturnValue_1) == 0x000018, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_GetIndianaUI_Branches) == 0x000020, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_GetIndianaUI_Branches' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_GetIndianaUI_ReturnValue) == 0x000028, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_GetIndianaUI_ReturnValue' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_GetGameInstance_ReturnValue) == 0x000030, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_ConstructUserWidget_Branches) == 0x000038, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_ConstructUserWidget_Branches' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_ConstructUserWidget_ReturnValue) == 0x000040, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_ConstructUserWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, K2Node_DynamicCast_AsIndiana_Game_Instance) == 0x000048, "Member 'Main_C_ExecuteUbergraph_Main::K2Node_DynamicCast_AsIndiana_Game_Instance' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'Main_C_ExecuteUbergraph_Main::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, K2Node_SwitchEnum_CmpSuccess) == 0x000051, "Member 'Main_C_ExecuteUbergraph_Main::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, K2Node_SwitchEnum_CmpSuccess_1) == 0x000052, "Member 'Main_C_ExecuteUbergraph_Main::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_Multiply_RotatorFloat_ReturnValue) == 0x000054, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_Multiply_RotatorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_K2_AddActorWorldRotation_SweepHitResult) == 0x000060, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_K2_AddActorWorldRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Main_C_ExecuteUbergraph_Main, CallFunc_K2_AddActorWorldRotation_SweepHitResult_1) == 0x0000E8, "Member 'Main_C_ExecuteUbergraph_Main::CallFunc_K2_AddActorWorldRotation_SweepHitResult_1' has a wrong offset!");

// Function Main.Main_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Main_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Main_C_ReceiveTick) == 0x000004, "Wrong alignment on Main_C_ReceiveTick");
static_assert(sizeof(Main_C_ReceiveTick) == 0x000004, "Wrong size on Main_C_ReceiveTick");
static_assert(offsetof(Main_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Main_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

