#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainDLCManager_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass MainDLCManager_BP.MainDLCManager_BP_C
// 0x0000 (0x0330 - 0x0330)
class UMainDLCManager_BP_C final : public UMainMenuDLCManagerWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainDLCManager_BP_C">();
	}
	static class UMainDLCManager_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainDLCManager_BP_C>();
	}
};
static_assert(alignof(UMainDLCManager_BP_C) == 0x000008, "Wrong alignment on UMainDLCManager_BP_C");
static_assert(sizeof(UMainDLCManager_BP_C) == 0x000330, "Wrong size on UMainDLCManager_BP_C");

}

