#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"


namespace CG::Params
{

// Function MainMenu.MainMenu_C.ExecuteUbergraph_MainMenu
// 0x0118 (0x0118 - 0x0000)
struct MainMenu_C_ExecuteUbergraph_MainMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0044(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0054(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_Event_bShouldChangeLogo;                    // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29E7[0x3];                                     // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_2;              // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_3;              // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_4;              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_5;              // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_6;              // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_7;              // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRenderOpacity_ReturnValue;             // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_FloatFloat_ReturnValue;        // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29E8[0x3];                                     // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRenderOpacity_ReturnValue_1;           // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29E9[0x3];                                     // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRenderOpacity_ReturnValue_2;           // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29EA[0x3];                                     // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x00C0(0x0010)(ZeroConstructor, NoDestructor)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_8;              // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_9;              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_10;             // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_11;             // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_12;             // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x00F8(0x0010)(ZeroConstructor, NoDestructor)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_13;             // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_14;             // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MainMenu_C_ExecuteUbergraph_MainMenu) == 0x000008, "Wrong alignment on MainMenu_C_ExecuteUbergraph_MainMenu");
static_assert(sizeof(MainMenu_C_ExecuteUbergraph_MainMenu) == 0x000118, "Wrong size on MainMenu_C_ExecuteUbergraph_MainMenu");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, EntryPoint) == 0x000000, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_2) == 0x000024, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_3) == 0x000034, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_4) == 0x000044, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_5) == 0x000054, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_Event_bShouldChangeLogo) == 0x000064, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_Event_bShouldChangeLogo' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue) == 0x000068, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_1) == 0x000070, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_2) == 0x000078, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_3) == 0x000080, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_4) == 0x000088, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_5) == 0x000090, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_6) == 0x000098, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_7) == 0x0000A0, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_GetRenderOpacity_ReturnValue) == 0x0000A8, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_GetRenderOpacity_ReturnValue' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_EqualEqual_FloatFloat_ReturnValue) == 0x0000AC, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_EqualEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_GetRenderOpacity_ReturnValue_1) == 0x0000B0, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_GetRenderOpacity_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_Greater_FloatFloat_ReturnValue) == 0x0000B4, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_GetRenderOpacity_ReturnValue_2) == 0x0000B8, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_GetRenderOpacity_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x0000BC, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_6) == 0x0000C0, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_8) == 0x0000D0, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_9) == 0x0000D8, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_10) == 0x0000E0, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_11) == 0x0000E8, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_12) == 0x0000F0, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, K2Node_CreateDelegate_OutputDelegate_7) == 0x0000F8, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_13) == 0x000108, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(MainMenu_C_ExecuteUbergraph_MainMenu, CallFunc_PlayAnimation_ReturnValue_14) == 0x000110, "Member 'MainMenu_C_ExecuteUbergraph_MainMenu::CallFunc_PlayAnimation_ReturnValue_14' has a wrong offset!");

// Function MainMenu.MainMenu_C.OnShowInterface
// 0x0001 (0x0001 - 0x0000)
struct MainMenu_C_OnShowInterface final
{
public:
	bool                                          bShouldChangeLogo;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(MainMenu_C_OnShowInterface) == 0x000001, "Wrong alignment on MainMenu_C_OnShowInterface");
static_assert(sizeof(MainMenu_C_OnShowInterface) == 0x000001, "Wrong size on MainMenu_C_OnShowInterface");
static_assert(offsetof(MainMenu_C_OnShowInterface, bShouldChangeLogo) == 0x000000, "Member 'MainMenu_C_OnShowInterface::bShouldChangeLogo' has a wrong offset!");

// Function MainMenu.MainMenu_C.FadeInMenu
// 0x0001 (0x0001 - 0x0000)
struct MainMenu_C_FadeInMenu final
{
public:
	bool                                          Condition;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(MainMenu_C_FadeInMenu) == 0x000001, "Wrong alignment on MainMenu_C_FadeInMenu");
static_assert(sizeof(MainMenu_C_FadeInMenu) == 0x000001, "Wrong size on MainMenu_C_FadeInMenu");
static_assert(offsetof(MainMenu_C_FadeInMenu, Condition) == 0x000000, "Member 'MainMenu_C_FadeInMenu::Condition' has a wrong offset!");

}

