#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Main

#include "Basic.hpp"

#include "Indiana_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace CG
{

// BlueprintGeneratedClass Main.Main_C
// 0x0030 (0x02F0 - 0x02C0)
class AMain_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FRotator                               Rotation_Speed;                                    // 0x02C8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29EB[0x4];                                     // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ACineCameraActor*                       MM_Cam_ExecuteUbergraph_Main_RefProperty;          // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_StarField_C*                        BP_StarField2_ExecuteUbergraph_Main_RefProperty;   // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AEmitter*                               PS_Stars_11_ExecuteUbergraph_Main_RefProperty;     // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Main(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Main_C">();
	}
	static class AMain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMain_C>();
	}
};
static_assert(alignof(AMain_C) == 0x000008, "Wrong alignment on AMain_C");
static_assert(sizeof(AMain_C) == 0x0002F0, "Wrong size on AMain_C");
static_assert(offsetof(AMain_C, UberGraphFrame) == 0x0002C0, "Member 'AMain_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AMain_C, Rotation_Speed) == 0x0002C8, "Member 'AMain_C::Rotation_Speed' has a wrong offset!");
static_assert(offsetof(AMain_C, MM_Cam_ExecuteUbergraph_Main_RefProperty) == 0x0002D8, "Member 'AMain_C::MM_Cam_ExecuteUbergraph_Main_RefProperty' has a wrong offset!");
static_assert(offsetof(AMain_C, BP_StarField2_ExecuteUbergraph_Main_RefProperty) == 0x0002E0, "Member 'AMain_C::BP_StarField2_ExecuteUbergraph_Main_RefProperty' has a wrong offset!");
static_assert(offsetof(AMain_C, PS_Stars_11_ExecuteUbergraph_Main_RefProperty) == 0x0002E8, "Member 'AMain_C::PS_Stars_11_ExecuteUbergraph_Main_RefProperty' has a wrong offset!");

}

