#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "Indiana_classes.hpp"
#include "Engine_structs.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass MainMenu.MainMenu_C
// 0x0068 (0x0460 - 0x03F8)
class UMainMenu_C final : public UMainMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeInGammaSelection;                              // 0x0400(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       AutosaveSplashAnimation;                           // 0x0408(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeInKeyPress;                                    // 0x0410(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeInLogo;                                        // 0x0418(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeOutLogo;                                       // 0x0420(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       KeyPressFadeLowAnim;                               // 0x0428(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeOutOptionsMenu;                                // 0x0430(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 LogoImage;                                         // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USavingSpinnerWidget_BP_C*              SavingSpinnerWidget;                               // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USavingWidget_BP_C*                     SavingWidget_BP;                                   // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUserWidget*                            NewVar_0;                                          // 0x0458(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MainMenu(int32 EntryPoint);
	void OnGammaSelectionFadeInComplete();
	void OnStartShowMainOptions();
	void OnStartHideAnyTextComplete();
	void OnStartShowGammaComplete();
	void OnStartShowGammaSelection();
	void OnStartHideGammaSelection();
	void OnHideLogo();
	void OnStartHideGammaSelectionComplete();
	void OnStartShowMainOptionsComplete();
	void FadeOutOptionsMenuFinished();
	void OnShowLogo();
	void FadeInKeyPressEvent();
	void OnAutosaveSplashCompleteEvent();
	void StartAutosaveSplash();
	void OnShowAnyTextPrompt();
	void OnPromptFadeInComplete();
	void OnStartHideAnyTextPrompt();
	void OnShowInterface(bool bShouldChangeLogo);
	void OnHideInterface();
	void Construct();
	void FadeInMenu(bool Condition);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainMenu_C">();
	}
	static class UMainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainMenu_C>();
	}
};
static_assert(alignof(UMainMenu_C) == 0x000008, "Wrong alignment on UMainMenu_C");
static_assert(sizeof(UMainMenu_C) == 0x000460, "Wrong size on UMainMenu_C");
static_assert(offsetof(UMainMenu_C, UberGraphFrame) == 0x0003F8, "Member 'UMainMenu_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, FadeInGammaSelection) == 0x000400, "Member 'UMainMenu_C::FadeInGammaSelection' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, AutosaveSplashAnimation) == 0x000408, "Member 'UMainMenu_C::AutosaveSplashAnimation' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, FadeInKeyPress) == 0x000410, "Member 'UMainMenu_C::FadeInKeyPress' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, FadeInLogo) == 0x000418, "Member 'UMainMenu_C::FadeInLogo' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, FadeOutLogo) == 0x000420, "Member 'UMainMenu_C::FadeOutLogo' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, KeyPressFadeLowAnim) == 0x000428, "Member 'UMainMenu_C::KeyPressFadeLowAnim' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, FadeOutOptionsMenu) == 0x000430, "Member 'UMainMenu_C::FadeOutOptionsMenu' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, Image_0) == 0x000438, "Member 'UMainMenu_C::Image_0' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, LogoImage) == 0x000440, "Member 'UMainMenu_C::LogoImage' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, SavingSpinnerWidget) == 0x000448, "Member 'UMainMenu_C::SavingSpinnerWidget' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, SavingWidget_BP) == 0x000450, "Member 'UMainMenu_C::SavingWidget_BP' has a wrong offset!");
static_assert(offsetof(UMainMenu_C, NewVar_0) == 0x000458, "Member 'UMainMenu_C::NewVar_0' has a wrong offset!");

}

