#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainOptions_BP

#include "Basic.hpp"

#include "MainOptions_BP_classes.hpp"
#include "MainOptions_BP_parameters.hpp"


namespace CG
{

// Function MainOptions_BP.MainOptions_BP_C.ExecuteUbergraph_MainOptions_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainOptions_BP_C::ExecuteUbergraph_MainOptions_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "ExecuteUbergraph_MainOptions_BP");

	Params::MainOptions_BP_C_ExecuteUbergraph_MainOptions_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_43_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_42_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_41_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ChangeProfileButton_K2Node_ComponentBoundEvent_40_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_31_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_30_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_29_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__CreditsButton_K2Node_ComponentBoundEvent_28_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_27_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_26_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_25_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_24_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_23_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_22_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_21_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_20_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_19_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_18_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_17_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_16_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_14_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_13_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_12_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_11_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_10_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_9_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_8_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_7_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__QuitButton_K2Node_ComponentBoundEvent_6_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__SettingsButton_K2Node_ComponentBoundEvent_5_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__LoadSaveButton_K2Node_ComponentBoundEvent_4_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__NewGameButton_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ExtrasButton_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__DeliverablesButton_K2Node_ComponentBoundEvent_1_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainOptions_BP.MainOptions_BP_C.BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UMainOptions_BP_C::BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainOptions_BP_C", "BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature");

	Params::MainOptions_BP_C_BndEvt__ContinueButton_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}

}

