#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "MainMenu_classes.hpp"
#include "MainMenu_parameters.hpp"


namespace CG
{

// Function MainMenu.MainMenu_C.ExecuteUbergraph_MainMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_C::ExecuteUbergraph_MainMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ExecuteUbergraph_MainMenu");

	Params::MainMenu_C_ExecuteUbergraph_MainMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.OnGammaSelectionFadeInComplete
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnGammaSelectionFadeInComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnGammaSelectionFadeInComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartShowMainOptions
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnStartShowMainOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartShowMainOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartHideAnyTextComplete
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnStartHideAnyTextComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartHideAnyTextComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartShowGammaComplete
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnStartShowGammaComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartShowGammaComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartShowGammaSelection
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnStartShowGammaSelection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartShowGammaSelection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartHideGammaSelection
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnStartHideGammaSelection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartHideGammaSelection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnHideLogo
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnHideLogo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnHideLogo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartHideGammaSelectionComplete
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnStartHideGammaSelectionComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartHideGammaSelectionComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartShowMainOptionsComplete
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnStartShowMainOptionsComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartShowMainOptionsComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.FadeOutOptionsMenuFinished
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::FadeOutOptionsMenuFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "FadeOutOptionsMenuFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnShowLogo
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnShowLogo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnShowLogo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.FadeInKeyPressEvent
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::FadeInKeyPressEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "FadeInKeyPressEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnAutosaveSplashCompleteEvent
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnAutosaveSplashCompleteEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnAutosaveSplashCompleteEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.StartAutosaveSplash
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::StartAutosaveSplash()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "StartAutosaveSplash");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnShowAnyTextPrompt
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnShowAnyTextPrompt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnShowAnyTextPrompt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnPromptFadeInComplete
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_C::OnPromptFadeInComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnPromptFadeInComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnStartHideAnyTextPrompt
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnStartHideAnyTextPrompt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnStartHideAnyTextPrompt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnShowInterface
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShouldChangeLogo                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainMenu_C::OnShowInterface(bool bShouldChangeLogo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnShowInterface");

	Params::MainMenu_C_OnShowInterface Parms{};

	Parms.bShouldChangeLogo = bShouldChangeLogo;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.OnHideInterface
// (Event, Protected, BlueprintEvent)

void UMainMenu_C::OnHideInterface()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnHideInterface");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.FadeInMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Condition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainMenu_C::FadeInMenu(bool Condition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "FadeInMenu");

	Params::MainMenu_C_FadeInMenu Parms{};

	Parms.Condition = Condition;

	UObject::ProcessEvent(Func, &Parms);
}

}

