#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SavingSpinnerWidget_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass SavingSpinnerWidget_BP.SavingSpinnerWidget_BP_C
// 0x0018 (0x0318 - 0x0300)
class USavingSpinnerWidget_BP_C final : public UIndianaUserWidget
{
public:
	class UImage*                                 SavingImageBacking;                                // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SavingImageForeground;                             // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SavingImageRotating;                               // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SavingSpinnerWidget_BP_C">();
	}
	static class USavingSpinnerWidget_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USavingSpinnerWidget_BP_C>();
	}
};
static_assert(alignof(USavingSpinnerWidget_BP_C) == 0x000008, "Wrong alignment on USavingSpinnerWidget_BP_C");
static_assert(sizeof(USavingSpinnerWidget_BP_C) == 0x000318, "Wrong size on USavingSpinnerWidget_BP_C");
static_assert(offsetof(USavingSpinnerWidget_BP_C, SavingImageBacking) == 0x000300, "Member 'USavingSpinnerWidget_BP_C::SavingImageBacking' has a wrong offset!");
static_assert(offsetof(USavingSpinnerWidget_BP_C, SavingImageForeground) == 0x000308, "Member 'USavingSpinnerWidget_BP_C::SavingImageForeground' has a wrong offset!");
static_assert(offsetof(USavingSpinnerWidget_BP_C, SavingImageRotating) == 0x000310, "Member 'USavingSpinnerWidget_BP_C::SavingImageRotating' has a wrong offset!");

}

